# Week 08: Local/Global Variables

## 0. Import Libraries 

In [2]:
# the "pandas" library is for manipualting datasets
import pandas as pd
import numpy as np
np.random.seed(100)

## 1. Array Continued (Stacking)

<font size='4'>

In [3]:
# 9.1.
x = np.ones((4,))
print(x)
print()
my_array = np.array([1,2,3,4])
my_resized_array=np.resize(my_array,(2,4))
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Concatentate `my_array` and `x`
print(np.concatenate([my_array, x], axis=0))
print()
print(np.stack([my_array, x], axis=0))
print()
print(np.stack([my_array, x], axis=1))

[1. 1. 1. 1.]

[1. 2. 3. 4. 1. 1. 1. 1.]

[[1. 2. 3. 4.]
 [1. 1. 1. 1.]]

[[1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]]


In [4]:
# 9.2. Stack arrays row-wise (by Python's default)


In [5]:
# 9.3.
my_array = np.array([1,2,3,4])
my_resized_array=np.resize(my_array,(2,4))
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# if the second argument is an integer, it will split the array into an N equal sub-arrays
# Split `my_stacked_array` horizontally into two equal sub-arrays

# Split `my_stacked_array` vertically into two equal sub-arrays


In [ ]:
# 9.4. Use indices in the form of a numpy array


In [6]:
# 9.5. Let's create a practical example and call back from the blood pressue problem.
# (2, 10, 5) refers to two sites, 10 patients each site, and 5 time points per patient.
BP_3d_arr = np.random.uniform(low=70, high=100, size=(2, 10, 5))
# print(BP_3d_arr)
# print(BP_3d_arr.shape)

In [11]:
# 9.5.1 axis takes one number


In [14]:
# 9.5.2 axis takes two numbers


In [13]:
# 9.5.3. axis takes three numbers or None


## 2. Local and Global Variables

<font size="4"> 

Most of the variables we've defined so far are "global"

- Stored in working environment
- Can be referenced in other parts of the notebook



<font size = "5">
Example:

In [9]:
message_hello = "hello"
number3       = 3

In [10]:
print(message_hello + " world")
print(number3 * 2)

hello world
6


<font size = "4">

Any "global" variable can be referenced inside functions

- However, this can lead to mistakes
- Preferrably, include **all** the inputs as parameters

<font size = "4">

$f(x,y,z) = x + y + z$

In [9]:
# 2.1. Correct Example:


8
13


In [10]:
# 2.2. Example that runs (but not recommended)
# Python will try to fill in any missing inputs
# with variables in the working environment


8
13


In [11]:
# 2.2.1.
del z # remove variables from a global scope


NameError: name 'z' is not defined

<font size ="4">

Variables defined inside functions are "local"

- Stored "temporarily" while running
- Includes: Parameters + Intermediate variables


### Local variables supercede global variables

In [ ]:
# 2.3.


In [ ]:
# 2.4. An exception


In [ ]:
# 2.5. This is an example where we define a quadratic function
# (x,y) are both local variables of the function
# 
# When we call the function, only the arguments matter.
# any intermediate value inside the function are "invisible"
# or "inaccessible" when exiting the function.


### Local variables are **not** stored in the working environment

In [ ]:
# 2.6. The following code assigns a global variable x


### To permanently modify a variable, use the "global" command

In [ ]:
# 2.7.


### Try it yourself:

<font size = "4">
    
- What happens if we run `modify_x` twice?
- What happens if we add `global y` inside `fn_square`?

In [ ]:
# 2.8. Write your own code here


In [ ]:
# 2.9.


### Built-in scope (Variables defined in Python)

<font size='4'>

- Functions such as `print()`, `len()`, `sum()`, `isinstance()` are all built-in functions in Python.
- They are available in any part of your code, so no need to define them.
- Python has a list of variables that are always available to prevent you from using the same names.
- Most of them are error names.

In [ ]:
# 2.10


### Enclosing scope (Variables defined in enclosing functions)

<font size='4'>
    
- They refer to variables defined in enclosing functions
- Enclosing functions are functions that contain other functions (nested or hierarachical functions)
- Enclosing scope is between local and global scopes in the LEGB rule

In [ ]:
# 2.11
# Define a function that contains another function


## 3. Work with Python scripts

<font size='4'>

Please open `week_08_main_1.py` and `week_08_main_2.py`.